tasks:
  - name: vscode
    before: |
      mkdir $GITPOD_REPO_ROOT/.vscode/
      touch $GITPOD_REPO_ROOT/.vscode/settings.json
      echo "{\"workbench.colorTheme\": \"Gitpod Dark\"}" >> $GITPOD_REPO_ROOT/.vscode/settings.json